name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  examples:
    runs-on: ubuntu-latest
    name: Test example ${{ matrix.project }}
    strategy:
      fail-fast: false
      matrix:
        project:
          - browser-to-server
          - browser-to-browser
    defaults:
      run:
        working-directory: examples/${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: npm install
        working-directory: .
      - name: Build root
        run: npm run build
        working-directory: .
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
        env:
          CI: true
